errF(): Refactor for clarity
Signed-off-by: Dimitar Yurukov <mscalindt@protonmail.com>

diff --git a/src/errF b/src/errF
--- a/src/errF
+++ b/src/errF
@@ -2,11 +2,11 @@
 # Print red-colored formatted text to stderr and exit
 #! .params:
 # <$1> - exit code
-# <$2> - type(
+# <$2> - format(
 #     '-' - raw
-#     '--' - raw, no linefeed
-#     '-date' - %H%M%S date fmt
-#     '-date-nolf' - %H%M%S date fmt, no linefeed
+#     '--' - raw; no linefeed
+#     '-date' - `date` %H%M%S
+#     '--date' - `date` %H%M%S; no linefeed
 #     .
 # )
 # <"$3"+> - text
@@ -14,13 +14,14 @@
 # [NO_COLOR] $ - environment variable;
 #                disables colored output
 #! .rc:
-# (*) success
+# (*)
 # (255) bad input
 #.
 errF() {
+    # Assert all required parameters are present.
     [ "$#" -ge 3 ] || return 255
 
-    # Check if $1 is a whole number
+    # Assert $1 is a whole number.
     case :"$1${1#*[!0123456789]}" in
         :) return 255 ;;
         :00) : ;;
@@ -29,57 +30,41 @@ errF() {
         *) return 255 ;;
     esac
 
+    # Assert $1 is a number in the range 0-255.
     [ "$1" -le 255 ] || return 255
 
-    _exit_code="$1"
-
+    # Check if color codes should be used.
     if [ "$NO_COLOR" ]; then
-        case $2 in
-            '-')
-                shift 2
-                printf "%s\n" "$*" >&2
-            ;;
-            '--')
-                shift 2
-                printf "%s" "$*" >&2
-            ;;
-            '-date')
-                shift 2
-                printf "[%s] =>>: %s\n" "$(date "+%H:%M:%S")" "$*" >&2
-            ;;
-            '-date-nolf')
-                shift 2
-                printf "[%s] =>>: %s" "$(date "+%H:%M:%S")" "$*" >&2
-            ;;
-            *)
-                return 255
-            ;;
-        esac
+        _color=; _reset=
     else
-        case $2 in
-            '-')
-                shift 2
-                printf "%b%s%b\n" '\033[1;31m' "$*" '\033[0m' >&2
-            ;;
-            '--')
-                shift 2
-                printf "%b%s%b" '\033[1;31m' "$*" '\033[0m' >&2
-            ;;
-            '-date')
-                shift 2
-                printf "%b[%s] =>>: %b%s%b\n" '\033[1;31m' \
-                    "$(date "+%H:%M:%S")" '\033[1;37m' "$*" '\033[0m' >&2
-            ;;
-            '-date-nolf')
-                shift 2
-                printf "%b[%s] =>>: %b%s%b" '\033[1;31m' \
-                    "$(date "+%H:%M:%S")" '\033[1;37m' "$*" '\033[0m' >&2
-            ;;
-            *)
-                return 255
-            ;;
-        esac
+        _color='\033[1;31m'; _reset='\033[0m'
     fi
 
-    exit "$_exit_code"
+    # Save the format into $_format and shift both the exit code ($1) and the
+    # format ($2) parameters; what will remain of $@ is the text parameter(s).
+    _code="$1"; _format="$2"; shift 2
+
+    # Print the specified format.
+    case "$_format" in
+        '-')
+            printf "%b%s%b\n" "$_color" "$*" "$_reset" >&2
+        ;;
+        '--')
+            printf "%b%s%b" "$_color" "$*" "$_reset" >&2
+        ;;
+        '-date')
+            printf "%b[%s] =>>: %s%b\n" "$_color" "$(date '+%H:%M:%S')" "$*" \
+                "$_reset" >&2
+        ;;
+        '--date')
+            printf "%b[%s] =>>: %s%b" "$_color" "$(date '+%H:%M:%S')" "$*" \
+                "$_reset" >&2
+        ;;
+        *)
+            return 255
+        ;;
+    esac
+
+    # Issue `exit` with the specified code.
+    exit "$_code"
 }
