opd_min(): Improve the output
Improve as in remove the unusual characters and unify it.

Signed-off-by: Dimitar Yurukov <mscalindt@protonmail.com>

diff --git a/src/opd_min b/src/opd_min
--- a/src/opd_min
+++ b/src/opd_min
@@ -14,7 +14,7 @@ opd_min() {
     printf "%s: Insufficient operands: %s\n" "${0##*/}" "$1" >&2
 
     if [ "$#" -ge 2 ]; then
-        printf " > min required: %s\n" "$2" >&2
+        printf "Minimum required: %s\n" "$2" >&2
     fi
 
     printf "%s: Try '%s --help' for more information.\n" \
