scopt_optional(): Refactor for clarity and robustness
Signed-off-by: Dimitar Yurukov <mscalindt@protonmail.com>

diff --git a/src/scopt_optional b/src/scopt_optional
--- a/src/scopt_optional
+++ b/src/scopt_optional
@@ -15,37 +15,34 @@
 #! .rc:
 # (0) match
 # (1) no match
+# (2) bad argument specification
 #.
 scopt_optional() {
-    scopt_optional_arg_invalid() {
-        printf "%s: Invalid argument specification for: '%s'\n" \
-            "${0##*/}" "$1"
-        printf "%s: Try '%s --help' for more information.\n" \
-            "${0##*/}" "${0##*/}"
-    } >&2
-
-    [ "$opt" ] || return 1
-
-    for _arg in "$@"; do
+    # Try to match the given option(s) possibly with an argument.
+    while [ "$1" ]; do
+        # The option cannot end with `=`, otherwise it's deemed invalid.
         case "$opt" in
-            "$_arg"'=')
-                scopt_optional_arg_invalid "$_arg"
-
+            "$1"'=')
+                printf "%s: Invalid argument specification for: '%s'\n" \
+                    "${0##*/}" "$1" >&2
+                printf "%s: Try '%s --help' for more information.\n" \
+                    "${0##*/}" "${0##*/}" >&2
                 exit 2
             ;;
-            "$_arg"'='*)
-                opt_arg="${opt#"$_arg"=}"; opt=; opt_match="$_arg"; \
-                shiftN=1
-
+            "$1"'='*)
+                opt_arg="${opt#"$1"=}"; opt=; opt_match="$1"; shiftN=1
                 return 0
             ;;
-            "$_arg")
-                opt=; opt_arg=; opt_match="$_arg"; shiftN=1
-
+            "$1")
+                opt_arg=; opt=; opt_match="$1"; shiftN=1
                 return 0
             ;;
         esac
+
+        # $1 (the current option) doesn't match; shift it to try the next one.
+        shift
     done
 
+    # No match.
     return 1
 }
