scopt(): Refactor for clarity and robustness
Signed-off-by: Dimitar Yurukov <mscalindt@protonmail.com>

diff --git a/src/scopt b/src/scopt
--- a/src/scopt
+++ b/src/scopt
@@ -1,43 +1,32 @@
 #! .desc:
-# True if specific complex (argument) option
+# Match specific option(s) with a mandatory option argument
 #! .params:
-# <"$1"+> - *
+# <"$1"+> - option(s)
 #! .uses:
 # <opt> $ - string;
-#           first positional parameter of the main environment
+#           first positional parameter
 # <opt_arg> $ - string;
-#               second positional parameter of the main environment
+#               second positional parameter
 #! .gives:
 # (0) <"$opt_arg"> - string;
 #                    option argument
 # (0) <"$opt_match"> - string;
 #                      literal option matched
-# (0) <$shiftN> - integer;
-#                 shift count
+# (0) <$opt_shift> - integer;
+#                    shift count for option
 #! .rc:
-# (0) match
+# (0) success
 # (1) no match
 #! .ec:
 # (2) bad argument specification
 #.
 scopt() {
-    # Try to match the given option(s) with an argument.
     while [ "$1" ]; do
-        # The option cannot end with `=`, otherwise it's deemed invalid.
-        case "$opt " in
-            "$1"'= ')
-                printf "%s: Invalid argument specification for: '%s'\n" \
-                    "${0##*/}" "$1" >&2
-                printf "%s: Try '%s --help' for more information.\n" \
-                    "${0##*/}" "${0##*/}" >&2
-                exit 2
-            ;;
-            "$1"'='*)
-                opt_arg="${opt#"$1"=}"; opt=; opt_match="$1"; shiftN=1
-                return 0
-            ;;
-            "$1"' ')
-                # Assert $opt_arg (the argument) is present.
+        # Try to match an option. The second positional parameter is presumably
+        # its argument.
+        case "$opt" in
+            "$1")
+                # Assert the second positional parameter is present.
                 if [ ! "$opt_arg" ]; then
                     printf "%s: Option '%s' requires an argument.\n" \
                         "${0##*/}" "$1" >&2
@@ -46,15 +35,42 @@ scopt() {
                     exit 2
                 fi
 
-                opt=; opt_match="$1"; shiftN=2
+                opt_match="$1"
+                opt_shift=2
+                opt=
+
                 return 0
             ;;
         esac
 
-        # $1 (the current option) doesn't match; shift it to try the next one.
+        # Assert any potential argument specification is valid. An option
+        # cannot end with `=` after being matched, otherwise it's invalid;
+        # example: `foo=`.
+        case "$opt" in
+            "$1"'=')
+                printf "%s: Invalid argument specification for: '%s'\n" \
+                    "${0##*/}" "$1" >&2
+                printf "%s: Try '%s --help' for more information.\n" \
+                    "${0##*/}" "${0##*/}" >&2
+                exit 2
+            ;;
+        esac
+
+        # Try to match an option with an argument separated by `=` on the same
+        # positional parameter; example: `foo=bar`.
+        case "$opt" in
+            "$1"'='*)
+                opt_arg="${opt#"$1"=}"
+                opt_match="$1"
+                opt_shift=1
+                opt=
+
+                return 0
+            ;;
+        esac
+
         shift
     done
 
-    # No match.
     return 1
 }
